name: Preflight

on:
  workflow_call:
    secrets:
      token:
        description: "The Broker token"
        required: true
      github_token:
        description: "GitHub token with repo read permissions"
        required: true
permissions: {}

jobs:
  check-jwt:
    name: Check broker token
    uses: ./.github/workflows/check-token.yaml
    secrets:
      token: ${{ secrets.token }}
  
  check-release-package:
    name: Check release package
    uses: ./.github/workflows/check-release-package.yaml
    secrets:
      token: ${{ secrets.github_token }}
      